import os
import psutil
import pyautogui
from datetime import datetime
from fpdf import FPDF

# Tentukan Folder Penyimpanan Laporan
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPORT_DIR = os.path.join(BASE_DIR, "storage", "reports")
os.makedirs(REPORT_DIR, exist_ok=True)

class SystemReport(FPDF):
    def header(self):
        # Header Laporan (Mirip Kop Surat)
        self.set_font('Arial', 'B', 16)
        self.set_text_color(0, 243, 255) # Warna Cyan Cyberpunk (di PDF jadi biru muda)
        self.cell(0, 10, 'IT OPS // SYSTEM STATUS REPORT', 0, 1, 'C')
        self.set_draw_color(0, 0, 0)
        self.line(10, 20, 200, 20)
        self.ln(10)

    def footer(self):
        # Footer (Halaman)
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Generated by JARVIS AI - Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, f'  {label}', 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 5, text)
        self.ln()

def generate_pdf():
    # 1. Siapkan Nama File
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    pdf_filename = f"REPORT_{timestamp}.pdf"
    pdf_path = os.path.join(REPORT_DIR, pdf_filename)
    
    # 2. Ambil Screenshot Bukti
    screenshot_path = os.path.join(REPORT_DIR, f"proof_{timestamp}.png")
    try:
        pyautogui.screenshot().save(screenshot_path)
    except:
        screenshot_path = None

    # 3. Kumpulkan Data Sistem
    cpu = psutil.cpu_percent(interval=1)
    ram = psutil.virtual_memory()
    disk = psutil.disk_usage('/')
    battery = psutil.sensors_battery()
    
    # Format Status Baterai
    batt_status = "No Battery / PC"
    if battery:
        batt_status = f"{battery.percent}% ({'Charging' if battery.power_plugged else 'On Battery'})"

    # 4. Mulai Menulis PDF
    pdf = SystemReport()
    pdf.add_page()
    
    # --- BAGIAN 1: INFO WAKTU ---
    pdf.set_text_color(0)
    pdf.chapter_title(f'TIMESTAMP: {datetime.now().strftime("%d %B %Y, %H:%M:%S")}')
    
    # --- BAGIAN 2: HARDWARE METRICS ---
    pdf.chapter_title('HARDWARE TELEMETRY')
    stats = (
        f"CPU Load      : {cpu}%\n"
        f"RAM Usage     : {ram.percent}% (Used: {round(ram.used/1e9, 2)} GB / Total: {round(ram.total/1e9, 2)} GB)\n"
        f"Disk (C:)     : {disk.percent}% Used\n"
        f"Power Status  : {batt_status}\n"
        f"System Uptime : {round((datetime.now().timestamp() - psutil.boot_time()) / 3600, 2)} Hours"
    )
    pdf.chapter_body(stats)

    # --- BAGIAN 3: VISUAL PROOF (GAMBAR) ---
    if screenshot_path and os.path.exists(screenshot_path):
        pdf.chapter_title('VISUAL SURVEILLANCE (SCREENSHOT)')
        # Masukkan gambar (x=10, y=current, w=190 mm)
        pdf.image(screenshot_path, x=10, w=190)
        # Hapus gambar aslinya biar hemat storage, karena sudah masuk PDF
        os.remove(screenshot_path)
    
    # 5. Simpan PDF
    pdf.output(pdf_path)
    print(f"📄 Report Generated: {pdf_path}")
    return pdf_path

# Test kalau dijalankan langsung
if __name__ == "__main__":
    generate_pdf()